CREATE SCHEMA CUSTOMERS;

CREATE TABLE CUSTOMERS (
    ID INT NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    AGE INT NOT NULL,
    ADDRESS CHAR(25),
    SALARY DECIMAL(18,2),
    PRIMARY KEY (ID)
);

INSERT INTO CUSTOMERS 
VALUES (1, 'Ramesh', 32, 'Ahmedabad', 2000.00);
INSERT INTO CUSTOMERS 
VALUES (2, 'Khilan', 25, 'Delhi', 1500.00);
INSERT INTO CUSTOMERS 
VALUES (3, 'Kaushik', 23, 'Kota', 2000.00);
INSERT INTO CUSTOMERS 
VALUES (4, 'Chaitali', 25, 'Mumbai', 6500.00);
INSERT INTO CUSTOMERS 
VALUES (5, 'Hardik', 27, 'Bhopal', 8500);
INSERT INTO CUSTOMERS 
VALUES (6, 'Komal', 22, 'MP', 4500.00);
INSERT INTO CUSTOMERS 
VALUES (7, 'Muffy', 24, 'Indore', 10000.00);
INSERT INTO CUSTOMERS (ID, NAME, AGE , SALARY)
VALUES (8, 'Mohan', 24, 1500.00 );

select * from customers;

select id, name, salary from customers;

select * from customers
where salary > 2000;

select count(*) from customers
where salary > 2000;

SELECT * FROM customers
WHERE NAME = 'HARDIK';

select * from customers 
where salary > 2000 and age < 25;

select * from customers 
where salary > 2000 OR age < 25;

UPDATE CUSTOMERS 
SET ADDRESS = 'PUNE'
WHERE ID = 6;

SELECT * FROM CUSTOMERS;

SELECT * FROM CUSTOMERS 
WHERE SALARY LIKE '200%'; 

SELECT * FROM CUSTOMERS 
WHERE SALARY LIKE '%200%';

SELECT * FROM CUSTOMERS 
WHERE SALARY LIKE '00%';

SELECT * FROM CUSTOMERS 
WHERE SALARY LIKE '%00';

SELECT * FROM CUSTOMERS 
WHERE SALARY LIKE '_00%';

SELECT * FROM CUSTOMERS 
WHERE SALARY LIKE '2_%';

SELECT * FROM CUSTOMERS 
WHERE SALARY LIKE '2%';

SELECT * FROM CUSTOMERS
LIMIT 3;

SELECT * FROM CUSTOMERS 
ORDER BY NAME;

SELECT * FROM CUSTOMERS 
ORDER BY NAME, SALARY;

SELECT * FROM CUSTOMERS 
ORDER BY SALARY DESC;

CREATE TABLE ORDERS (
    OID INT NOT NULL,
    DATE DATE NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    AMOUNT INT NOT NULL,
    PRIMARY KEY (OID)
);

INSERT INTO ORDERS
VALUES (102, '2009-10-08 00:00:00', 3, 3000);

INSERT INTO ORDERS
VALUES (100, '2009-10-08 00:00:00', 3, 1500);

INSERT INTO ORDERS
VALUES (101, '2009-11-20 00:00:00', 2, 1560);

INSERT INTO ORDERS
VALUES (103, '2009-05-20 00:00:00', 4, 2060);

-- JOINS --

SELECT ID, NAME, AGE, AMOUNT,OID, DATE
FROM CUSTOMERS, ORDERS
WHERE CUSTOMERS.ID = ORDERS.CUSTOMER_ID;


-- INNER JOIN --

SELECT ID, NAME , AMOUNT, DATE 
FROM CUSTOMERS 
INNER JOIN ORDERS 
ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID;

-- LEFT JOIN--

SELECT ID, NAME, AMOUNT, DATE
FROM CUSTOMERS
LEFT JOIN ORDERS
ON  CUSTOMERS.ID = ORDERS.CUSTOMER_ID;

-- RIGHT JOIN --

SELECT ID, NAME, AMOUNT, DATE
FROM CUSTOMERS
RIGHT JOIN ORDERS
ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID;

-- FULL JOINS --

SELECT ID, NAME, AMOUNT, DATE
FROM CUSTOMERS
LEFT JOIN ORDERS
ON  CUSTOMERS.ID = ORDERS.CUSTOMER_ID
UNION ALL
SELECT ID, NAME, AMOUNT, DATE
FROM CUSTOMERS
RIGHT JOIN ORDERS
ON CUSTOMERS.ID = ORDERS.CUSTOMER_ID;

-- SELF JOIN --

SELECT A.ID, B.NAME, A.SALARY
FROM CUSTOMERS A, CUSTOMERS B
WHERE A.SALARY < B.SALARY;





















 



